name: Clippy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: operator

      - name: Clippy check lints
        run: cargo clippy -- -D warnings
