name: Validate controller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-controller:
    runs-on: ubuntu-latest

    services:
      postgresql:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Generate CRD
        run: cargo run --bin=crdgen >> crd.yaml

      - name: Apply CRD
        run: kubectl apply -f crd.yaml

      - name: Build Controller
        run: docker build -t controller .

      - name: Apply manifests
        run: kubectl apply -f test/manifest.yaml

      - name: Validate if CRD is working
        run: |
          kubectl get pod -n project
