name: Validate controller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          cluster_name: "k8scluster"

      - name: Generate CRD
        run: cargo run --bin=crdgen >> crd.yaml

      - name: Apply CRD
        run: kubectl apply -f crd.yaml

      - name: Build Controller
        run: docker build -t ext-cardano-dbsync:1.0 .

      - name: Load Image into Kind
        run: kind load docker-image ext-cardano-dbsync:1.0 --name k8scluster

      - name: Apply manifest
        run: kubectl apply -f test/manifest.yaml

      - name: Wait containers is ready
        run: sleep 8;

      - name: Apply manifests
        run: kubectl apply -f test/dbsyncport.yaml

      - name: Validate if CRD is working
        run: |
          # kubectl describe dbsyncports.demeter.run --namespace project useraccess | grep -oP 'Username:  \K\S+'
          # kubectl describe dbsyncports.demeter.run --namespace project useraccess | grep -oP 'Password:  \K\S+'
          counter=0; while ((counter++ < 6)); do kubectl logs -n project "$(kubectl get pods -n project | grep -oP 'controller-\w+-\w+')"; sleep 2; done;
          kubectl describe dbsyncports.demeter.run --namespace project useraccess

      # - name: Collect controller status
      #   run: |
      #     kubectl describe dbsyncports.demeter.run --namespace project useraccess | grep -oP 'Password:  \K\S+'
      #     kubectl describe dbsyncports.demeter.run --namespace project useraccess | grep -oP 'Username:  \K\S+'
