name: Validate controller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Generate CRD
        run: cargo run --bin=crdgen >> crd.yaml

      - name: Apply CRD
        run: kubectl apply -f crd.yaml

      - name: Validate if CRD is working
        run: |
          kubectl get customresourcedefinitions.apiextensions.k8s.io -o wide
