name: Validate controller

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-controller:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0

      - name: Validate if Kind is working
        run: |
          kubectl get nodes -o wide
          kubectl get pods --all-namespaces -o wide
          kubectl get services --all-namespaces -o wide
